INSERT INTO formengine_mail_configuration (form, senderName, senderMail, object)
VALUES ('etatcivil', 'Etat civil de la Ville de Paris', 'ne_pas_repondre@paris.fr', 'Non utilis� dans ETAT CIVIL');

--
-- Dumping data in table formengine_group_notice
--
INSERT INTO formengine_group_notice (id_group_notice,title,id_form,is_enabled,workgroup_key) VALUES 
  (1,'deces-lieuEtDate-remarqueLieu','9',1,'all');
INSERT INTO formengine_group_notice (id_group_notice,title,id_form,is_enabled,workgroup_key) VALUES 
  (2,'mariage-lieuEtDate-remarqueLieu','18',1,'all');
INSERT INTO formengine_group_notice (id_group_notice,title,id_form,is_enabled,workgroup_key) VALUES 
  (3,'naissance-lieuEtDate-remarqueLieu','0',1,'all');
INSERT INTO formengine_group_notice (id_group_notice,title,id_form,is_enabled,workgroup_key) VALUES 
  (4,'reconnaissance-lieuEtDate-remarqueLieu','27',1,'all');
INSERT INTO formengine_group_notice (id_group_notice,title,id_form,is_enabled,workgroup_key) VALUES 
  (5,'deces-choixActe-remarquesTypesActes','14',1,'all');
INSERT INTO formengine_group_notice (id_group_notice,title,id_form,is_enabled,workgroup_key) VALUES 
  (6,'deces-infosComplementaires-remarqueEmail','10',1,'all');
INSERT INTO formengine_group_notice (id_group_notice,title,id_form,is_enabled,workgroup_key) VALUES 
  (7,'deces-validation-legislation','12',1,'all');
INSERT INTO formengine_group_notice (id_group_notice,title,id_form,is_enabled,workgroup_key) VALUES 
  (8,'mariage-choixActe-remarquesTypesActes','23',1,'all');
INSERT INTO formengine_group_notice (id_group_notice,title,id_form,is_enabled,workgroup_key) VALUES 
  (9,'mariage-infosComplementaires-remarqueEmail','19',1,'all');
INSERT INTO formengine_group_notice (id_group_notice,title,id_form,is_enabled,workgroup_key) VALUES 
  (10,'mariage-validation-legislation','21',1,'all');
INSERT INTO formengine_group_notice (id_group_notice,title,id_form,is_enabled,workgroup_key) VALUES 
  (11,'naissance-choixActe-remarquesTypesActes','5',1,'all');
INSERT INTO formengine_group_notice (id_group_notice,title,id_form,is_enabled,workgroup_key) VALUES 
  (12,'naissance-infosComplementaires-remarqueEmail','1',1,'all');
INSERT INTO formengine_group_notice (id_group_notice,title,id_form,is_enabled,workgroup_key) VALUES 
  (13,'naissance-validation-legislation','3',1,'all');
INSERT INTO formengine_group_notice (id_group_notice,title,id_form,is_enabled,workgroup_key) VALUES 
  (14,'reconnaissance-identiteReconnaissance-remarqueIdentiteParent','31',1,'all');
INSERT INTO formengine_group_notice (id_group_notice,title,id_form,is_enabled,workgroup_key) VALUES 
  (15,'reconnaissance-infosComplementaires-remarqueEmail','28',1,'all');
INSERT INTO formengine_group_notice (id_group_notice,title,id_form,is_enabled,workgroup_key) VALUES 
  (16,'reconnaissance-validation-legislation','29',1,'all');
INSERT INTO formengine_group_notice (id_group_notice,title,id_form,is_enabled,workgroup_key) VALUES 
  (17,'deces-lieuEtDate-remarqueLieu','8',1,'all');
INSERT INTO formengine_group_notice (id_group_notice,title,id_form,is_enabled,workgroup_key) VALUES 
  (18,'deces-choixActe-remarquesTypesActes','7',1,'all');
INSERT INTO formengine_group_notice (id_group_notice,title,id_form,is_enabled,workgroup_key) VALUES 
  (19,'mariage-lieuEtDate-remarqueLieu','17',1,'all');
INSERT INTO formengine_group_notice (id_group_notice,title,id_form,is_enabled,workgroup_key) VALUES 
  (20,'mariage-choixActe-remarquesTypesActes','16',1,'all');
INSERT INTO formengine_group_notice (id_group_notice,title,id_form,is_enabled,workgroup_key) VALUES 
  (21,'naissance-lieuEtDate-remarqueLieu','26',1,'all');
INSERT INTO formengine_group_notice (id_group_notice,title,id_form,is_enabled,workgroup_key) VALUES 
  (22,'naissance-choixActe-remarquesTypesActes','25',1,'all');
INSERT INTO formengine_group_notice (id_group_notice,title,id_form,is_enabled,workgroup_key) VALUES 
  (23,'reconnaissance-lieuEtDate-remarqueLieu','33',1,'all');

--
-- Dumping data in table formengine_notice
--
INSERT INTO formengine_notice (id_notice,title,message,workgroup_key,date_debut,date_fin,id_diffusion,is_enabled,id_notification,notice_order,id_notice_group) VALUES 
  (1,'deces-lieuEtDate-remarqueLieu','\n                    Seuls les actes enregistrés à Paris peuvent être délivrés.\n                    Les actes de décès sont enregistrés à la mairie (d''arrondissement) du lieu du décès et, éventuellement\n		    transcrits, à la mairie (d''arrondissement) du dernier domicile du défunt. \n                    Pour plus d''informations, veuillez consulter \n                     \n                    <a target=\_blank\ href=\http://www.service-public.fr\>service-public.fr</a>\n                    .\n                ','all',NULL,NULL,-1,1,0,0,1);
INSERT INTO formengine_notice (id_notice,title,message,workgroup_key,date_debut,date_fin,id_diffusion,is_enabled,id_notification,notice_order,id_notice_group) VALUES 
  (2,'deces-lieuEtDate-remarqueDate','\n                \n                  <p>\n                  Les actes d''état civil détenus par les mairies d''arrondissement ne \n                  concernent que la période postérieure à 1903. Si le décès a eu lieu avant 1903, \n                  la demande doit être faite au : \n      			  </p>\n    			  <blockquote>\n    			        <p> \n    			        Service des Archives départementales<br />\n    			        18 boulevard Sérurier<br/>\n    			        75019 Paris <br/>\n    			        Tél : 01 53 72 41 23 \n    			        </p>\n    			        <p>\n    			        <a target=\parent\ href=\http://www.paris.fr/portail/Culture/Portal.lut?page_id=149\><span class=\aquo\>&raquo; </span>Lien vers les archives de Paris</a>\n    			        </p>\n    			      </blockquote>\n                \n                ','all',NULL,NULL,-1,1,0,0,1);
INSERT INTO formengine_notice (id_notice,title,message,workgroup_key,date_debut,date_fin,id_diffusion,is_enabled,id_notification,notice_order,id_notice_group) VALUES 
  (3,'deces-choixActe-remarquesTypesActes','\n             Une copie intégrale est une reproduction de l''acte original, \n             mentions marginales comprises.\n            ','all',NULL,NULL,-1,1,0,0,5);
INSERT INTO formengine_notice (id_notice,title,message,workgroup_key,date_debut,date_fin,id_diffusion,is_enabled,id_notification,notice_order,id_notice_group) VALUES 
  (4,'deces-choixActe-remarquesTypesActes','\n               Un extrait plurilingue est un extrait d''acte d''état civil destiné à être utilisé à l''étranger.   \n            ','all',NULL,NULL,-1,1,0,0,5);
INSERT INTO formengine_notice (id_notice,title,message,workgroup_key,date_debut,date_fin,id_diffusion,is_enabled,id_notification,notice_order,id_notice_group) VALUES 
  (5,'deces-infosComplementaires-remarqueEmail','\n               Si vous indiquez votre adresse mèl, vous recevrez un accusé de réception de la demande.\n            ','all',NULL,NULL,-1,1,0,0,6);
INSERT INTO formengine_notice (id_notice,title,message,workgroup_key,date_debut,date_fin,id_diffusion,is_enabled,id_notification,notice_order,id_notice_group) VALUES 
  (6,'deces-validation-legislation','\n        L''acte vous sera acheminé par voie postale et non par courrier électronique.\n        En effet, l''absence de textes légaux ou réglementaires sur la sécurisation des échanges \n        et la reconnaissance juridique de la signature électronique, ne permet pas pour le moment \n        la transmission par voie télématique des copies ou des extraits d''actes d''état civil.\n          ','all',NULL,NULL,-1,1,0,0,7);
INSERT INTO formengine_notice (id_notice,title,message,workgroup_key,date_debut,date_fin,id_diffusion,is_enabled,id_notification,notice_order,id_notice_group) VALUES 
  (7,'deces-validation-legislation','\n        En application de l''article 441-7 du code pénal, est puni d''un an d''emprisonnement et de 15000 euros\n        d''amende le fait :  \n                \n          <ul>\n            <li>D''établir une attestation ou un certificat faisant état de faits matériellement inexacts.</li>\n            <li>De falsifier une attestation ou un certificat originairement sincère</li>\n            <li>De faire usage d''une attestation ou d''un certificat inexact ou falsifié</li>\n          </ul>\n        \n          ','all',NULL,NULL,-1,1,0,0,7);
INSERT INTO formengine_notice (id_notice,title,message,workgroup_key,date_debut,date_fin,id_diffusion,is_enabled,id_notification,notice_order,id_notice_group) VALUES 
  (8,'mariage-lieuEtDate-remarqueLieu','\n                    Seuls les actes enregistrés à Paris peuvent être délivrés.\n                    Si le mariage a eu lieu dans une autre commune, \n                    veuillez consulter \n                     \n                    <a target=\_blank\ href=\http://www.service-public.fr\>service-public.fr</a>\n                    .\n                ','all',NULL,NULL,-1,1,0,0,2);
INSERT INTO formengine_notice (id_notice,title,message,workgroup_key,date_debut,date_fin,id_diffusion,is_enabled,id_notification,notice_order,id_notice_group) VALUES 
  (9,'mariage-lieuEtDate-remarqueDate','\n                \n                  <p>\n                  Les actes d''état civil détenus par les mairies d''arrondissement ne \n                  concernent que la période postérieure à 1903. Si le mariage a eu lieu avant 1903, \n                  la demande doit être faite au : \n      			  </p>\n    			  <blockquote>\n    			        <p> \n    			        Service des Archives départementales<br />\n    			        18 boulevard Sérurier<br/>\n    			        75019 Paris <br/>\n    			        Tél : 01 53 72 41 23 \n    			        </p>\n    			        <p>\n    			        <a target=\parent\ href=\http://www.paris.fr/portail/Culture/Portal.lut?page_id=149\><span class=\aquo\>&raquo; </span>Lien vers les archives de Paris</a>\n    			        </p>\n    			      </blockquote>\n                \n                ','all',NULL,NULL,-1,1,0,0,2);
INSERT INTO formengine_notice (id_notice,title,message,workgroup_key,date_debut,date_fin,id_diffusion,is_enabled,id_notification,notice_order,id_notice_group) VALUES 
  (10,'mariage-lieuEtDate-remarqueLien','\n		Les notaires, les avocats, les représentants légaux et les administrations \n		spécifiquement autorisées qui peuvent avoir accès aux actes de l''état civil \n		de la personne qui leur a donné mandat sont invités à formuler leur demande \n		de copie intégrale ou d''extrait avec filiation de mariage \n		par courrier et non par Internet compte tenu de la nécessité de produire un \n		justificatif.\n            ','all',NULL,NULL,-1,1,0,0,2);
INSERT INTO formengine_notice (id_notice,title,message,workgroup_key,date_debut,date_fin,id_diffusion,is_enabled,id_notification,notice_order,id_notice_group) VALUES 
  (11,'mariage-choixActe-remarquesTypesActes','\n             Une copie intégrale est une reproduction de l''acte original, \n             mentions marginales comprises.\n            ','all',NULL,NULL,-1,1,0,0,8);
INSERT INTO formengine_notice (id_notice,title,message,workgroup_key,date_debut,date_fin,id_diffusion,is_enabled,id_notification,notice_order,id_notice_group) VALUES 
  (12,'mariage-choixActe-remarquesTypesActes','\n              Un extrait avec filiation regroupe l''identité de l''intéressé et les dernières mentions concernant \n              sa vie et sa situation familiale (décès, dernier mariage, divorce ...). \n              S''il contient les noms et prénoms des parents de l''intéressé, l''extrait s''appelle \n              extrait avec filiation.  \n            ','all',NULL,NULL,-1,1,0,0,8);
INSERT INTO formengine_notice (id_notice,title,message,workgroup_key,date_debut,date_fin,id_diffusion,is_enabled,id_notification,notice_order,id_notice_group) VALUES 
  (13,'mariage-choixActe-remarquesTypesActes','\n             Un extrait sans filiation ne contient pas les noms et prénoms des parents de l''intéressé. \n            ','all',NULL,NULL,-1,1,0,0,8);
INSERT INTO formengine_notice (id_notice,title,message,workgroup_key,date_debut,date_fin,id_diffusion,is_enabled,id_notification,notice_order,id_notice_group) VALUES 
  (14,'mariage-choixActe-remarquesTypesActes','\n               Un extrait plurilingue est un extrait d''acte d''état civil destiné à être utilisé à l''étranger.   \n            ','all',NULL,NULL,-1,1,0,0,8);
INSERT INTO formengine_notice (id_notice,title,message,workgroup_key,date_debut,date_fin,id_diffusion,is_enabled,id_notification,notice_order,id_notice_group) VALUES 
  (15,'mariage-choixActe-informations','\n                \n               <p> Pour obtenir une copie intégrale ou un extrait avec filiation d''acte de mariage, le demandeur doit satisfaire 3 conditions (décret n° 97-852 du 16 septembre 1997) :\n                </p>\n                <ul>\n                <li>\n                Etre la personne que l''acte concerne, son conjoint, ses ascendants ou descendants, son représentant légal.\n                </li>\n                <li>\n                Etre majeur ou émancipé.\n                </li>\n                <li>\n                Etre en mesure d''indiquer, lors de la demande, les nom et prénom usuels des parents de la personne concernée par l''acte.\n                </li>\n                </ul>\n                <p>\n                Toute personne peut obtenir un extrait sans filiation d''acte de naissance.\n                </p>\n                \n            ','all',NULL,NULL,-1,1,0,0,8);
INSERT INTO formengine_notice (id_notice,title,message,workgroup_key,date_debut,date_fin,id_diffusion,is_enabled,id_notification,notice_order,id_notice_group) VALUES 
  (16,'mariage-infosComplementaires-remarqueEmail','\n               Si vous indiquez votre adresse mèl, vous recevrez un accusé de réception de la demande.\n            ','all',NULL,NULL,-1,1,0,0,9);
INSERT INTO formengine_notice (id_notice,title,message,workgroup_key,date_debut,date_fin,id_diffusion,is_enabled,id_notification,notice_order,id_notice_group) VALUES 
  (17,'mariage-validation-legislation','\n        L''acte vous sera acheminé par voie postale et non par courrier électronique.\n        En effet, l''absence de textes légaux ou réglementaires sur la sécurisation des échanges \n        et la reconnaissance juridique de la signature électronique, ne permet pas pour le moment \n        la transmission par voie télématique des copies ou des extraits d''actes d''état civil.\n          ','all',NULL,NULL,-1,1,0,0,10);
INSERT INTO formengine_notice (id_notice,title,message,workgroup_key,date_debut,date_fin,id_diffusion,is_enabled,id_notification,notice_order,id_notice_group) VALUES 
  (18,'mariage-validation-legislation','\n        En application de l''article 441-7 du code pénal, est puni d''un an d''emprisonnement et de 15000 euros\n        d''amende le fait :  \n                \n          <ul>\n            <li>D''établir une attestation ou un certificat faisant état de faits matériellement inexacts.</li>\n            <li>De falsifier une attestation ou un certificat originairement sincère</li>\n            <li>De faire usage d''une attestation ou d''un certificat inexact ou falsifié</li>\n          </ul>\n        \n          ','all',NULL,NULL,-1,1,0,0,10);
INSERT INTO formengine_notice (id_notice,title,message,workgroup_key,date_debut,date_fin,id_diffusion,is_enabled,id_notification,notice_order,id_notice_group) VALUES 
  (19,'naissance-lieuEtDate-remarqueLieu','\n                    Seuls les actes enregistrés à Paris peuvent être délivrés.\n                    Si la naissance a eu lieu dans une autre commune,\n                    veuillez consulter\n                     \n                    <a target=\_blank\ href=\http://www.service-public.fr\>service-public.fr</a>\n                    .\n                ','all',NULL,NULL,-1,1,0,0,3);
INSERT INTO formengine_notice (id_notice,title,message,workgroup_key,date_debut,date_fin,id_diffusion,is_enabled,id_notification,notice_order,id_notice_group) VALUES 
  (20,'naissance-lieuEtDate-remarqueDate','\n                \n                  <p>\n                  Les actes d''état civil détenus par les mairies d''arrondissement ne\n                  concernent que la période postérieure à 1903. Si la naissance a eu lieu avant 1903,\n                  la demande doit être faite au :\n      			  </p>\n    			  <blockquote>\n    			        <p>\n    			        Service des Archives départementales<br />\n    			        18 boulevard Sérurier<br/>\n    			        75019 Paris <br/>\n    			        Tél : 01 53 72 41 23\n    			        </p>\n    			        <p>\n    			        <a target=\parent\ href=\http://www.paris.fr/portail/Culture/Portal.lut?page_id=149\><span class=\aquo\>&raquo; </span>Lien vers les archives de Paris</a>\n    			        </p>\n    			      </blockquote>\n                \n                ','all',NULL,NULL,-1,1,0,0,3);
INSERT INTO formengine_notice (id_notice,title,message,workgroup_key,date_debut,date_fin,id_diffusion,is_enabled,id_notification,notice_order,id_notice_group) VALUES 
  (21,'naissance-lieuEtDate-remarqueLien','\n		Les notaires, les avocats, les représentants légaux et les administrations \n		spécifiquement autorisées qui peuvent avoir accès aux actes de l''état civil \n		de la personne qui leur a donné mandat sont invités à formuler leur demande \n		de copie intégrale ou d''extrait avec filiation de naissance \n		par courrier et non par Internet compte tenu de la nécessité de produire un \n		justificatif.\n            ','all',NULL,NULL,-1,1,0,0,3);
INSERT INTO formengine_notice (id_notice,title,message,workgroup_key,date_debut,date_fin,id_diffusion,is_enabled,id_notification,notice_order,id_notice_group) VALUES 
  (22,'naissance-choixActe-remarquesTypesActes','\n             Une copie intégrale est une reproduction de l''acte original,\n             mentions marginales comprises.\n            ','all',NULL,NULL,-1,1,0,0,11);
INSERT INTO formengine_notice (id_notice,title,message,workgroup_key,date_debut,date_fin,id_diffusion,is_enabled,id_notification,notice_order,id_notice_group) VALUES 
  (23,'naissance-choixActe-remarquesTypesActes','\n              Un extrait avec filiation regroupe l''identité de l''intéressé et les dernières mentions concernant\n              sa vie et sa situation familiale (décès, dernier mariage, divorce ...).\n              S''il contient les noms et prénoms des parents de l''intéressé, l''extrait s''appelle\n              extrait avec filiation.  \n            ','all',NULL,NULL,-1,1,0,0,11);
INSERT INTO formengine_notice (id_notice,title,message,workgroup_key,date_debut,date_fin,id_diffusion,is_enabled,id_notification,notice_order,id_notice_group) VALUES 
  (24,'naissance-choixActe-remarquesTypesActes','\n             Un extrait sans filiation ne contient pas les noms et prénoms des parents de l''intéressé.\n            ','all',NULL,NULL,-1,1,0,0,11);
INSERT INTO formengine_notice (id_notice,title,message,workgroup_key,date_debut,date_fin,id_diffusion,is_enabled,id_notification,notice_order,id_notice_group) VALUES 
  (25,'naissance-choixActe-remarquesTypesActes','\n               Un extrait plurilingue est un extrait d''acte d''état civil destiné à être utilisé à l''étranger.\n            ','all',NULL,NULL,-1,1,0,0,11);
INSERT INTO formengine_notice (id_notice,title,message,workgroup_key,date_debut,date_fin,id_diffusion,is_enabled,id_notification,notice_order,id_notice_group) VALUES 
  (26,'naissance-choixActe-informations','\n                \n               <p> Pour obtenir une copie intégrale ou un extrait avec filiation d''acte de naissance, le demandeur doit satisfaire 3 conditions (décret n° 97-852 du 16 septembre 1997) :\n                </p>\n                <ul>\n                <li>\n                Etre la personne que l''acte concerne, son conjoint, ses ascendants ou descendants, son représentant légal.\n                </li>\n                <li>\n                Etre majeur ou émancipé.\n                </li>\n                <li>\n                Etre en mesure d''indiquer, lors de la demande, les nom et prénom usuels des parents de la personne concernée par l''acte.\n                </li>\n                </ul>\n                <p>\n                Toute personne peut obtenir un extrait sans filiation d''acte de naissance.\n                </p>\n                \n            ','all',NULL,NULL,-1,1,0,0,11);
INSERT INTO formengine_notice (id_notice,title,message,workgroup_key,date_debut,date_fin,id_diffusion,is_enabled,id_notification,notice_order,id_notice_group) VALUES 
  (27,'naissance-infosComplementaires-remarqueEmail','\n               Si vous indiquez votre adresse mèl, vous recevrez un accusé de réception de la demande.\n            ','all',NULL,NULL,-1,1,0,0,12);
INSERT INTO formengine_notice (id_notice,title,message,workgroup_key,date_debut,date_fin,id_diffusion,is_enabled,id_notification,notice_order,id_notice_group) VALUES 
  (28,'naissance-validation-legislation','\n        L''acte vous sera acheminé par voie postale et non par courrier électronique.\n        En effet, l''absence de textes légaux ou réglementaires sur la sécurisation des échanges \n        et la reconnaissance juridique de la signature électronique, ne permet pas pour le moment \n        la transmission par voie télématique des copies ou des extraits d''actes d''état civil.\n          ','all',NULL,NULL,-1,1,0,0,13);
INSERT INTO formengine_notice (id_notice,title,message,workgroup_key,date_debut,date_fin,id_diffusion,is_enabled,id_notification,notice_order,id_notice_group) VALUES 
  (29,'naissance-validation-legislation','\n        En application de l''article 441-7 du code pénal, est puni d''un an d''emprisonnement et de 15000 euros\n        d''amende le fait :  \n                \n          <ul>\n            <li>D''établir une attestation ou un certificat faisant état de faits matériellement inexacts.</li>\n            <li>De falsifier une attestation ou un certificat originairement sincère</li>\n            <li>De faire usage d''une attestation ou d''un certificat inexact ou falsifié</li>\n          </ul>\n        \n          ','all',NULL,NULL,-1,1,0,0,13);
INSERT INTO formengine_notice (id_notice,title,message,workgroup_key,date_debut,date_fin,id_diffusion,is_enabled,id_notification,notice_order,id_notice_group) VALUES 
  (30,'reconnaissance-lieuEtDate-remarqueLieu','\n                                Seuls les actes enregistrés à Paris peuvent être délivrés.\n                                Si la reconnaissance a eu lieu dans une autre commune, \n                                veuillez consulter \n                                 \n                                <a target=\_blank\ href=\http://www.service-public.fr\>service-public.fr</a>\n                                .\n                            ','all',NULL,NULL,-1,1,0,0,4);
INSERT INTO formengine_notice (id_notice,title,message,workgroup_key,date_debut,date_fin,id_diffusion,is_enabled,id_notification,notice_order,id_notice_group) VALUES 
  (31,'reconnaissance-lieuEtDate-remarqueDateNonConnue','\n                            Si vous ne connaissez pas la date de la reconnaissance, cette information\n                             peut éventuellement apparaître dans l''acte de naissance.\n                            ','all',NULL,NULL,-1,1,0,0,4);
INSERT INTO formengine_notice (id_notice,title,message,workgroup_key,date_debut,date_fin,id_diffusion,is_enabled,id_notification,notice_order,id_notice_group) VALUES 
  (32,'reconnaissance-lieuEtDate-remarqueDate','\n                            \n                              <p>\n                              Les actes d''état civil détenus par les mairies d''arrondissement ne \n                              concernent que la période postérieure à 1903. Si la reconnaissance a eu lieu avant 1903, \n                              la demande doit être faite au : \n                  			  </p>\n                			  <blockquote>\n                			        <p> \n                			        Service des Archives départementales<br />\n                			        18 boulevard Sérurier<br/>\n                			        75019 Paris <br/>\n                			        Tél : 01 53 72 41 23 \n                			        </p>\n                			        <p>\n                			        <a target=\parent\ href=\http://www.paris.fr/portail/Culture/Portal.lut?page_id=149\><span class=\aquo\>&raquo; </span>Lien vers les archives de Paris</a>\n                			        </p>\n                			      </blockquote>\n                            \n                           ','all',NULL,NULL,-1,1,0,0,4);
INSERT INTO formengine_notice (id_notice,title,message,workgroup_key,date_debut,date_fin,id_diffusion,is_enabled,id_notification,notice_order,id_notice_group) VALUES 
  (33,'reconnaissance-lieuEtDate-remarquenotaires','\n					Les notaires, les avocats, les représentants légaux et les administrations \n					spécifiquement autorisées qui peuvent avoir accès aux actes de l''état civil \n					de la personne qui leur a donné mandat sont invités à formuler leur demande \n					de copie intégrale de reconnaissance par courrier et non par Internet compte tenu de la nécessité de produire un \n					justificatif.\n			        ','all',NULL,NULL,-1,1,0,0,4);
INSERT INTO formengine_notice (id_notice,title,message,workgroup_key,date_debut,date_fin,id_diffusion,is_enabled,id_notification,notice_order,id_notice_group) VALUES 
  (34,'reconnaissance-identiteReconnaissance-remarqueIdentiteParent','\n                                Le nom et le prénom du père OU de la mère doivent être spécifiés.\n                            ','all',NULL,NULL,-1,1,0,0,14);
INSERT INTO formengine_notice (id_notice,title,message,workgroup_key,date_debut,date_fin,id_diffusion,is_enabled,id_notification,notice_order,id_notice_group) VALUES 
  (35,'reconnaissance-identiteReconnaissance-conditionsDelivrance','\n				Les actes de reconnaissance ne se délivrent que sous la forme de copie intégrale.\n				Ils peuvent être délivrées uniquement à la personne reconnue dans l''acte de \n				reconnaissance, ses ascendants, ses descendants, son conjoint ou son représentant \n				légal (décret n° 97-852 du 16 septembre 1997) .\n                            ','all',NULL,NULL,-1,1,0,0,14);
INSERT INTO formengine_notice (id_notice,title,message,workgroup_key,date_debut,date_fin,id_diffusion,is_enabled,id_notification,notice_order,id_notice_group) VALUES 
  (36,'reconnaissance-infosComplementaires-remarqueEmail','\n                                   Si vous indiquez votre adresse mèl, vous recevrez un accusé de réception de la demande.\n                                ','all',NULL,NULL,-1,1,0,0,15);
INSERT INTO formengine_notice (id_notice,title,message,workgroup_key,date_debut,date_fin,id_diffusion,is_enabled,id_notification,notice_order,id_notice_group) VALUES 
  (37,'reconnaissance-validation-legislation','\n                        L''acte vous sera acheminé par voie postale et non par courrier électronique.\n                        En effet, l''absence de textes légaux ou réglementaires sur la sécurisation des échanges \n                        et la reconnaissance juridique de la signature électronique, ne permet pas pour le moment \n                        la transmission par voie télématique des copies ou des extraits d''actes d''état civil.\n                        ','all',NULL,NULL,-1,1,0,0,16);
INSERT INTO formengine_notice (id_notice,title,message,workgroup_key,date_debut,date_fin,id_diffusion,is_enabled,id_notification,notice_order,id_notice_group) VALUES 
  (38,'reconnaissance-validation-legislation','\n                        En application de l''article 441-7 du code pénal, est puni d''un an d''emprisonnement et de 15000 euros\n                        d''amende le fait :  \n                        \n                         <ul>\n                           <li>D''établir une attestation ou un certificat faisant état de faits matériellement inexacts.</li>\n                           <li>De falsifier une attestation ou un certificat originairement sincère</li>\n                           <li>De faire usage d''une attestation ou d''un certificat inexact ou falsifié</li>\n                         </ul>\n                        \n                        ','all',NULL,NULL,-1,1,0,0,16);
INSERT INTO formengine_notice (id_notice,title,message,workgroup_key,date_debut,date_fin,id_diffusion,is_enabled,id_notification,notice_order,id_notice_group) VALUES 
  (39,'deces-lieuEtDate-remarqueLieu','\n                    Seuls les actes enregistrés à Paris peuvent être délivrés.\n                    Les actes de décès sont enregistrés à la mairie (d''arrondissement) du lieu du décès et, éventuellement\n		    transcrits, à la mairie (d''arrondissement) du dernier domicile du défunt. \n                    Pour plus d''informations, veuillez consulter \n                     \n                    <a target=\_blank\ href=\http://www.service-public.fr\>service-public.fr</a>\n                    .\n                ','all',NULL,NULL,-1,1,0,0,17);
INSERT INTO formengine_notice (id_notice,title,message,workgroup_key,date_debut,date_fin,id_diffusion,is_enabled,id_notification,notice_order,id_notice_group) VALUES 
  (40,'deces-lieuEtDate-remarqueDate','\n                \n                  <p>\n                  Les actes d''état civil détenus par les mairies d''arrondissement ne \n                  concernent que la période postérieure à 1903. Si le décès a eu lieu avant 1903, \n                  la demande doit être faite au : \n      			  </p>\n    			  <blockquote>\n    			        <p> \n    			        Service des Archives départementales<br />\n    			        18 boulevard Sérurier<br/>\n    			        75019 Paris <br/>\n    			        Tél : 01 53 72 41 23 \n    			        </p>\n    			        <p>\n    			        <a target=\parent\ href=\http://www.paris.fr/portail/Culture/Portal.lut?page_id=149\><span class=\aquo\>&raquo; </span>Lien vers les archives de Paris</a>\n    			        </p>\n    			      </blockquote>\n                \n                ','all',NULL,NULL,-1,1,0,0,17);
INSERT INTO formengine_notice (id_notice,title,message,workgroup_key,date_debut,date_fin,id_diffusion,is_enabled,id_notification,notice_order,id_notice_group) VALUES 
  (41,'deces-choixActe-remarquesTypesActes','\n             Une copie intégrale est une reproduction de l''acte original, \n             mentions marginales comprises.\n            ','all',NULL,NULL,-1,1,0,0,18);
INSERT INTO formengine_notice (id_notice,title,message,workgroup_key,date_debut,date_fin,id_diffusion,is_enabled,id_notification,notice_order,id_notice_group) VALUES 
  (42,'deces-choixActe-remarquesTypesActes','\n               Un extrait plurilingue est un extrait d''acte d''état civil destiné à être utilisé à l''étranger.   \n            ','all',NULL,NULL,-1,1,0,0,18);
INSERT INTO formengine_notice (id_notice,title,message,workgroup_key,date_debut,date_fin,id_diffusion,is_enabled,id_notification,notice_order,id_notice_group) VALUES 
  (43,'deces-infosComplementaires-remarqueEmail','\n               Si vous indiquez votre adresse mèl, vous recevrez un accusé de réception de la demande.\n            ','all',NULL,NULL,-1,1,0,0,11);
INSERT INTO formengine_notice (id_notice,title,message,workgroup_key,date_debut,date_fin,id_diffusion,is_enabled,id_notification,notice_order,id_notice_group) VALUES 
  (44,'deces-validation-legislation','\n        L''acte vous sera acheminé par voie postale et non par courrier électronique.\n        En effet, l''absence de textes légaux ou réglementaires sur la sécurisation des échanges \n        et la reconnaissance juridique de la signature électronique, ne permet pas pour le moment \n        la transmission par voie télématique des copies ou des extraits d''actes d''état civil.\n          ','all',NULL,NULL,-1,1,0,0,3);
INSERT INTO formengine_notice (id_notice,title,message,workgroup_key,date_debut,date_fin,id_diffusion,is_enabled,id_notification,notice_order,id_notice_group) VALUES 
  (45,'deces-validation-legislation','\n        En application de l''article 441-7 du code pénal, est puni d''un an d''emprisonnement et de 15000 euros\n        d''amende le fait :  \n                \n          <ul>\n            <li>D''établir une attestation ou un certificat faisant état de faits matériellement inexacts.</li>\n            <li>De falsifier une attestation ou un certificat originairement sincère</li>\n            <li>De faire usage d''une attestation ou d''un certificat inexact ou falsifié</li>\n          </ul>\n        \n          ','all',NULL,NULL,-1,1,0,0,3);
INSERT INTO formengine_notice (id_notice,title,message,workgroup_key,date_debut,date_fin,id_diffusion,is_enabled,id_notification,notice_order,id_notice_group) VALUES 
  (46,'mariage-lieuEtDate-remarqueLieu','\n                    Seuls les actes enregistrés à Paris peuvent être délivrés.\n                    Si le mariage a eu lieu dans une autre commune, \n                    veuillez consulter \n                     \n                    <a target=\_blank\ href=\http://www.service-public.fr\>service-public.fr</a>\n                    .\n                ','all',NULL,NULL,-1,1,0,0,19);
INSERT INTO formengine_notice (id_notice,title,message,workgroup_key,date_debut,date_fin,id_diffusion,is_enabled,id_notification,notice_order,id_notice_group) VALUES 
  (47,'mariage-lieuEtDate-remarqueDate','\n                \n                  <p>\n                  Les actes d''état civil détenus par les mairies d''arrondissement ne \n                  concernent que la période postérieure à 1903. Si le mariage a eu lieu avant 1903, \n                  la demande doit être faite au : \n      			  </p>\n    			  <blockquote>\n    			        <p> \n    			        Service des Archives départementales<br />\n    			        18 boulevard Sérurier<br/>\n    			        75019 Paris <br/>\n    			        Tél : 01 53 72 41 23 \n    			        </p>\n    			        <p>\n    			        <a target=\parent\ href=\http://www.paris.fr/portail/Culture/Portal.lut?page_id=149\><span class=\aquo\>&raquo; </span>Lien vers les archives de Paris</a>\n    			        </p>\n    			      </blockquote>\n                \n                ','all',NULL,NULL,-1,1,0,0,19);
INSERT INTO formengine_notice (id_notice,title,message,workgroup_key,date_debut,date_fin,id_diffusion,is_enabled,id_notification,notice_order,id_notice_group) VALUES 
  (48,'mariage-lieuEtDate-remarqueLien','\n		Les notaires, les avocats, les représentants légaux et les administrations \n		spécifiquement autorisées qui peuvent avoir accès aux actes de l''état civil \n		de la personne qui leur a donné mandat sont invités à formuler leur demande \n		de copie intégrale ou d''extrait avec filiation de mariage \n		par courrier et non par Internet compte tenu de la nécessité de produire un \n		justificatif.\n            ','all',NULL,NULL,-1,1,0,0,19);
INSERT INTO formengine_notice (id_notice,title,message,workgroup_key,date_debut,date_fin,id_diffusion,is_enabled,id_notification,notice_order,id_notice_group) VALUES 
  (49,'mariage-choixActe-remarquesTypesActes','\n             Une copie intégrale est une reproduction de l''acte original, \n             mentions marginales comprises.\n            ','all',NULL,NULL,-1,1,0,0,20);
INSERT INTO formengine_notice (id_notice,title,message,workgroup_key,date_debut,date_fin,id_diffusion,is_enabled,id_notification,notice_order,id_notice_group) VALUES 
  (50,'mariage-choixActe-remarquesTypesActes','\n              Un extrait avec filiation regroupe l''identité de l''intéressé et les dernières mentions concernant \n              sa vie et sa situation familiale (décès, dernier mariage, divorce ...). \n              S''il contient les noms et prénoms des parents de l''intéressé, l''extrait s''appelle \n              extrait avec filiation.  \n            ','all',NULL,NULL,-1,1,0,0,20);
INSERT INTO formengine_notice (id_notice,title,message,workgroup_key,date_debut,date_fin,id_diffusion,is_enabled,id_notification,notice_order,id_notice_group) VALUES 
  (51,'mariage-choixActe-remarquesTypesActes','\n             Un extrait sans filiation ne contient pas les noms et prénoms des parents de l''intéressé. \n            ','all',NULL,NULL,-1,1,0,0,20);
INSERT INTO formengine_notice (id_notice,title,message,workgroup_key,date_debut,date_fin,id_diffusion,is_enabled,id_notification,notice_order,id_notice_group) VALUES 
  (52,'mariage-choixActe-remarquesTypesActes','\n               Un extrait plurilingue est un extrait d''acte d''état civil destiné à être utilisé à l''étranger.   \n            ','all',NULL,NULL,-1,1,0,0,20);
INSERT INTO formengine_notice (id_notice,title,message,workgroup_key,date_debut,date_fin,id_diffusion,is_enabled,id_notification,notice_order,id_notice_group) VALUES 
  (53,'mariage-choixActe-informations','\n                \n               <p> Pour obtenir une copie intégrale ou un extrait avec filiation d''acte de mariage, le demandeur doit satisfaire 3 conditions (décret n° 97-852 du 16 septembre 1997) :\n                </p>\n                <ul>\n                <li>\n                Etre la personne que l''acte concerne, son conjoint, ses ascendants ou descendants, son représentant légal.\n                </li>\n                <li>\n                Etre majeur ou émancipé.\n                </li>\n                <li>\n                Etre en mesure d''indiquer, lors de la demande, les nom et prénom usuels des parents de la personne concernée par l''acte.\n                </li>\n                </ul>\n                <p>\n                Toute personne peut obtenir un extrait sans filiation d''acte de naissance.\n                </p>\n                \n            ','all',NULL,NULL,-1,1,0,0,20);
INSERT INTO formengine_notice (id_notice,title,message,workgroup_key,date_debut,date_fin,id_diffusion,is_enabled,id_notification,notice_order,id_notice_group) VALUES 
  (54,'mariage-infosComplementaires-remarqueEmail','\n               Si vous indiquez votre adresse mèl, vous recevrez un accusé de réception de la demande.\n            ','all',NULL,NULL,-1,1,0,0,5);
INSERT INTO formengine_notice (id_notice,title,message,workgroup_key,date_debut,date_fin,id_diffusion,is_enabled,id_notification,notice_order,id_notice_group) VALUES 
  (55,'mariage-validation-legislation','\n        L''acte vous sera acheminé par voie postale et non par courrier électronique.\n        En effet, l''absence de textes légaux ou réglementaires sur la sécurisation des échanges \n        et la reconnaissance juridique de la signature électronique, ne permet pas pour le moment \n        la transmission par voie télématique des copies ou des extraits d''actes d''état civil.\n          ','all',NULL,NULL,-1,1,0,0,1);
INSERT INTO formengine_notice (id_notice,title,message,workgroup_key,date_debut,date_fin,id_diffusion,is_enabled,id_notification,notice_order,id_notice_group) VALUES 
  (56,'mariage-validation-legislation','\n        En application de l''article 441-7 du code pénal, est puni d''un an d''emprisonnement et de 15000 euros\n        d''amende le fait :  \n                \n          <ul>\n            <li>D''établir une attestation ou un certificat faisant état de faits matériellement inexacts.</li>\n            <li>De falsifier une attestation ou un certificat originairement sincère</li>\n            <li>De faire usage d''une attestation ou d''un certificat inexact ou falsifié</li>\n          </ul>\n        \n          ','all',NULL,NULL,-1,1,0,0,1);
INSERT INTO formengine_notice (id_notice,title,message,workgroup_key,date_debut,date_fin,id_diffusion,is_enabled,id_notification,notice_order,id_notice_group) VALUES 
  (57,'naissance-lieuEtDate-remarqueLieu','\n                    Seuls les actes enregistrés à Paris peuvent être délivrés.\n                    Si la naissance a eu lieu dans une autre commune,\n                    veuillez consulter\n                     \n                    <a target=\_blank\ href=\http://www.service-public.fr\>service-public.fr</a>\n                    .\n                ','all',NULL,NULL,-1,1,0,0,21);
INSERT INTO formengine_notice (id_notice,title,message,workgroup_key,date_debut,date_fin,id_diffusion,is_enabled,id_notification,notice_order,id_notice_group) VALUES 
  (58,'naissance-lieuEtDate-remarqueDate','\n                \n                  <p>\n                  Les actes d''état civil détenus par les mairies d''arrondissement ne\n                  concernent que la période postérieure à 1903. Si la naissance a eu lieu avant 1903,\n                  la demande doit être faite au :\n      			  </p>\n    			  <blockquote>\n    			        <p>\n    			        Service des Archives départementales<br />\n    			        18 boulevard Sérurier<br/>\n    			        75019 Paris <br/>\n    			        Tél : 01 53 72 41 23\n    			        </p>\n    			        <p>\n    			        <a target=\parent\ href=\http://www.paris.fr/portail/Culture/Portal.lut?page_id=149\><span class=\aquo\>&raquo; </span>Lien vers les archives de Paris</a>\n    			        </p>\n    			      </blockquote>\n                \n                ','all',NULL,NULL,-1,1,0,0,21);
INSERT INTO formengine_notice (id_notice,title,message,workgroup_key,date_debut,date_fin,id_diffusion,is_enabled,id_notification,notice_order,id_notice_group) VALUES 
  (59,'naissance-lieuEtDate-remarqueLien','\n		Les notaires, les avocats, les représentants légaux et les administrations \n		spécifiquement autorisées qui peuvent avoir accès aux actes de l''état civil \n		de la personne qui leur a donné mandat sont invités à formuler leur demande \n		de copie intégrale ou d''extrait avec filiation de naissance \n		par courrier et non par Internet compte tenu de la nécessité de produire un \n		justificatif.\n            ','all',NULL,NULL,-1,1,0,0,21);
INSERT INTO formengine_notice (id_notice,title,message,workgroup_key,date_debut,date_fin,id_diffusion,is_enabled,id_notification,notice_order,id_notice_group) VALUES 
  (60,'naissance-choixActe-remarquesTypesActes','\n             Une copie intégrale est une reproduction de l''acte original,\n             mentions marginales comprises.\n            ','all',NULL,NULL,-1,1,0,0,22);
INSERT INTO formengine_notice (id_notice,title,message,workgroup_key,date_debut,date_fin,id_diffusion,is_enabled,id_notification,notice_order,id_notice_group) VALUES 
  (61,'naissance-choixActe-remarquesTypesActes','\n              Un extrait avec filiation regroupe l''identité de l''intéressé et les dernières mentions concernant\n              sa vie et sa situation familiale (décès, dernier mariage, divorce ...).\n              S''il contient les noms et prénoms des parents de l''intéressé, l''extrait s''appelle\n              extrait avec filiation.  \n            ','all',NULL,NULL,-1,1,0,0,22);
INSERT INTO formengine_notice (id_notice,title,message,workgroup_key,date_debut,date_fin,id_diffusion,is_enabled,id_notification,notice_order,id_notice_group) VALUES 
  (62,'naissance-choixActe-remarquesTypesActes','\n             Un extrait sans filiation ne contient pas les noms et prénoms des parents de l''intéressé.\n            ','all',NULL,NULL,-1,1,0,0,22);
INSERT INTO formengine_notice (id_notice,title,message,workgroup_key,date_debut,date_fin,id_diffusion,is_enabled,id_notification,notice_order,id_notice_group) VALUES 
  (63,'naissance-choixActe-remarquesTypesActes','\n               Un extrait plurilingue est un extrait d''acte d''état civil destiné à être utilisé à l''étranger.\n            ','all',NULL,NULL,-1,1,0,0,22);
INSERT INTO formengine_notice (id_notice,title,message,workgroup_key,date_debut,date_fin,id_diffusion,is_enabled,id_notification,notice_order,id_notice_group) VALUES 
  (64,'naissance-choixActe-informations','\n                \n               <p> Pour obtenir une copie intégrale ou un extrait avec filiation d''acte de naissance, le demandeur doit satisfaire 3 conditions (décret n° 97-852 du 16 septembre 1997) :\n                </p>\n                <ul>\n                <li>\n                Etre la personne que l''acte concerne, son conjoint, ses ascendants ou descendants, son représentant légal.\n                </li>\n                <li>\n                Etre majeur ou émancipé.\n                </li>\n                <li>\n                Etre en mesure d''indiquer, lors de la demande, les nom et prénom usuels des parents de la personne concernée par l''acte.\n                </li>\n                </ul>\n                <p>\n                Toute personne peut obtenir un extrait sans filiation d''acte de naissance.\n                </p>\n                \n            ','all',NULL,NULL,-1,1,0,0,22);
INSERT INTO formengine_notice (id_notice,title,message,workgroup_key,date_debut,date_fin,id_diffusion,is_enabled,id_notification,notice_order,id_notice_group) VALUES 
  (65,'naissance-infosComplementaires-remarqueEmail','\n               Si vous indiquez votre adresse mèl, vous recevrez un accusé de réception de la demande.\n            ','all',NULL,NULL,-1,1,0,0,8);
INSERT INTO formengine_notice (id_notice,title,message,workgroup_key,date_debut,date_fin,id_diffusion,is_enabled,id_notification,notice_order,id_notice_group) VALUES 
  (66,'naissance-validation-legislation','\n        L''acte vous sera acheminé par voie postale et non par courrier électronique.\n        En effet, l''absence de textes légaux ou réglementaires sur la sécurisation des échanges \n        et la reconnaissance juridique de la signature électronique, ne permet pas pour le moment \n        la transmission par voie télématique des copies ou des extraits d''actes d''état civil.\n          ','all',NULL,NULL,-1,1,0,0,2);
INSERT INTO formengine_notice (id_notice,title,message,workgroup_key,date_debut,date_fin,id_diffusion,is_enabled,id_notification,notice_order,id_notice_group) VALUES 
  (67,'naissance-validation-legislation','\n        En application de l''article 441-7 du code pénal, est puni d''un an d''emprisonnement et de 15000 euros\n        d''amende le fait :  \n                \n          <ul>\n            <li>D''établir une attestation ou un certificat faisant état de faits matériellement inexacts.</li>\n            <li>De falsifier une attestation ou un certificat originairement sincère</li>\n            <li>De faire usage d''une attestation ou d''un certificat inexact ou falsifié</li>\n          </ul>\n        \n          ','all',NULL,NULL,-1,1,0,0,2);
INSERT INTO formengine_notice (id_notice,title,message,workgroup_key,date_debut,date_fin,id_diffusion,is_enabled,id_notification,notice_order,id_notice_group) VALUES 
  (68,'reconnaissance-lieuEtDate-remarqueLieu','\n                                Seuls les actes enregistrés à Paris peuvent être délivrés.\n                                Si la reconnaissance a eu lieu dans une autre commune, \n                                veuillez consulter \n                                 \n                                <a target=\_blank\ href=\http://www.service-public.fr\>service-public.fr</a>\n                                .\n                            ','all',NULL,NULL,-1,1,0,0,23);
INSERT INTO formengine_notice (id_notice,title,message,workgroup_key,date_debut,date_fin,id_diffusion,is_enabled,id_notification,notice_order,id_notice_group) VALUES 
  (69,'reconnaissance-lieuEtDate-remarqueDateNonConnue','\n                            Si vous ne connaissez pas la date de la reconnaissance, cette information\n                             peut éventuellement apparaître dans l''acte de naissance.\n                            ','all',NULL,NULL,-1,1,0,0,23);
INSERT INTO formengine_notice (id_notice,title,message,workgroup_key,date_debut,date_fin,id_diffusion,is_enabled,id_notification,notice_order,id_notice_group) VALUES 
  (70,'reconnaissance-lieuEtDate-remarqueDate','\n                            \n                              <p>\n                              Les actes d''état civil détenus par les mairies d''arrondissement ne \n                              concernent que la période postérieure à 1903. Si la reconnaissance a eu lieu avant 1903, \n                              la demande doit être faite au : \n                  			  </p>\n                			  <blockquote>\n                			        <p> \n                			        Service des Archives départementales<br />\n                			        18 boulevard Sérurier<br/>\n                			        75019 Paris <br/>\n                			        Tél : 01 53 72 41 23 \n                			        </p>\n                			        <p>\n                			        <a target=\parent\ href=\http://www.paris.fr/portail/Culture/Portal.lut?page_id=149\><span class=\aquo\>&raquo; </span>Lien vers les archives de Paris</a>\n                			        </p>\n                			      </blockquote>\n                            \n                           ','all',NULL,NULL,-1,1,0,0,23);
INSERT INTO formengine_notice (id_notice,title,message,workgroup_key,date_debut,date_fin,id_diffusion,is_enabled,id_notification,notice_order,id_notice_group) VALUES 
  (71,'reconnaissance-lieuEtDate-remarquenotaires','\n					Les notaires, les avocats, les représentants légaux et les administrations \n					spécifiquement autorisées qui peuvent avoir accès aux actes de l''état civil \n					de la personne qui leur a donné mandat sont invités à formuler leur demande \n					de copie intégrale de reconnaissance par courrier et non par Internet compte tenu de la nécessité de produire un \n					justificatif.\n			        ','all',NULL,NULL,-1,1,0,0,23);
INSERT INTO formengine_notice (id_notice,title,message,workgroup_key,date_debut,date_fin,id_diffusion,is_enabled,id_notification,notice_order,id_notice_group) VALUES 
  (72,'reconnaissance-identiteReconnaissance-remarqueIdentiteParent','\n                                Le nom et le prénom du père OU de la mère doivent être spécifiés.\n                            ','all',NULL,NULL,-1,1,0,0,16);
INSERT INTO formengine_notice (id_notice,title,message,workgroup_key,date_debut,date_fin,id_diffusion,is_enabled,id_notification,notice_order,id_notice_group) VALUES 
  (73,'reconnaissance-identiteReconnaissance-conditionsDelivrance','\n				Les actes de reconnaissance ne se délivrent que sous la forme de copie intégrale.\n				Ils peuvent être délivrées uniquement à la personne reconnue dans l''acte de \n				reconnaissance, ses ascendants, ses descendants, son conjoint ou son représentant \n				légal (décret n° 97-852 du 16 septembre 1997) .\n                            ','all',NULL,NULL,-1,1,0,0,16);
INSERT INTO formengine_notice (id_notice,title,message,workgroup_key,date_debut,date_fin,id_diffusion,is_enabled,id_notification,notice_order,id_notice_group) VALUES 
  (74,'reconnaissance-infosComplementaires-remarqueEmail','\n                                   Si vous indiquez votre adresse mèl, vous recevrez un accusé de réception de la demande.\n                                ','all',NULL,NULL,-1,1,0,0,14);
INSERT INTO formengine_notice (id_notice,title,message,workgroup_key,date_debut,date_fin,id_diffusion,is_enabled,id_notification,notice_order,id_notice_group) VALUES 
  (75,'reconnaissance-validation-legislation','\n                        L''acte vous sera acheminé par voie postale et non par courrier électronique.\n                        En effet, l''absence de textes légaux ou réglementaires sur la sécurisation des échanges \n                        et la reconnaissance juridique de la signature électronique, ne permet pas pour le moment \n                        la transmission par voie télématique des copies ou des extraits d''actes d''état civil.\n                        ','all',NULL,NULL,-1,1,0,0,4);
INSERT INTO formengine_notice (id_notice,title,message,workgroup_key,date_debut,date_fin,id_diffusion,is_enabled,id_notification,notice_order,id_notice_group) VALUES 
  (76,'reconnaissance-validation-legislation','\n                        En application de l''article 441-7 du code pénal, est puni d''un an d''emprisonnement et de 15000 euros\n                        d''amende le fait :  \n                        \n                         <ul>\n                           <li>D''établir une attestation ou un certificat faisant état de faits matériellement inexacts.</li>\n                           <li>De falsifier une attestation ou un certificat originairement sincère</li>\n                           <li>De faire usage d''une attestation ou d''un certificat inexact ou falsifié</li>\n                         </ul>\n                        \n                        ','all',NULL,NULL,-1,1,0,0,4);
